# alembic.ini
[alembic]
# Chemin vers le dossier migrations
script_location = migrations

# Chemin vers les modules Python
prepend_sys_path = .

# Version courante
version_path_separator = os

# URL de la base de données (optionnel - peut être dans env.py)
sqlalchemy.url = postgresql+asyncpg://postgres:Pass%%4025%%23@127.0.0.1:5432/parier_keno

[post_write_hooks]
# hooks = black

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S