# Dockerfile.flask
# Interface web Flask

FROM python:3.12.3-slim

WORKDIR /app

# Installer les dépendances
COPY frontend-flask/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code
COPY frontend-flask/ .

# Créer un utilisateur non-root
RUN addgroup --system --gid 1000 appuser \
    && adduser --system --uid 1000 --gid 1000 appuser \
    && chown -R appuser:appuser /app

USER appuser

EXPOSE 5000

CMD ["python", "app.py"]